---
- name: hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    mode: '0644'

- name: install libselinux-python
  package:
    name: libselinux-python
    state: latest

- name: install vim
  package:
    name: vim-enhanced
    state: latest
